create table EMPLOYEE
(
	EMP_ID INT PRIMARY KEY, 
	ENAME VARCHAR(20), 
	DEPARTMENT VARCHAR(30), 
	MANAGER_ID INT,
	FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(EMP_ID)
);


INSERT INTO EMPLOYEE(EMP_ID, ENAME, DEPARTMENT, MANAGER_ID)
VALUES 
(1, 'A', 'AA', NULL),
(2, 'B', 'BB', 1),
(3, 'C', 'CC', 1),
(4, 'D', 'DD', 2);

SELECT E1.EMP_ID AS [EMPLOYEE ID], E1.ENAME AS [EMPLOYEE NAME],
		E2.DEPARTMENT AS [DEPARTMENT], E2.MANAGER_ID AS [MANAGER ID]

FROM EMPLOYEE AS E1
JOIN 
EMPLOYEE AS E2
ON
E1.MANAGER_ID = E2.EMP_ID;